### ISSUE TITLE
Compass' `font-files` and `font-url` produce wrong URLs when :relative_assets are enabled

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1087]
Hi.

I've got this line of Sass:

    +font-face(fontello, font-files('fontello.woff', 'fontello.ttf', 'fontello.svg'), 'fontello.eot', normal, normal)

It produces this piece of CSS:

```css
@font-face {
  font-family: "fontello";
  src: url("fonts/fontello.eot");
  src: url("fonts/fontello.eot?#iefix") format('eot'), url("fonts/fontello.woff") format('woff'), url("fonts/fontello.ttf") format('truetype'), url("fonts/fontello.svg") format('svg');
  font-weight: normal;
  font-style: normal; }
```

As you see, URLs are like this: `fonts/fontello.eot` while they should be like this: `../fonts/fontello.eot`, as i use defaults for assets placement and `:relative_assets` are enabled.

The problem does not happen all the time. If the problem takes place, restarting `bundle exec middleman server` may resolve it: Middleman may start producing correct font URLs. But then i edit the fonts Sass partial (simply add a blank line), and it produces wrong URLs again (this step is 100% reproducible). I restart Middleman, the problem persists. I restart Middleman again, the problem is gone.

This happens in a private project so i can't show the code via Github. But i temporarily share zipped sources via Dropbox (1 MiB):

https://www.dropbox.com/s/mh6j9zfl688qqcn/middleman-compass-fonst-url-problem.zip

Please have a look inside the zip for project structure, Gemfile.lock, config.rb, etc.

PS When i built the project, URLs appeared to be correct. I'm not sure whether the issue does not affect building or i was just lucky.
