### ISSUE TITLE
Default fonts directory includes 'source' directory in path.

### ISSUE THREAD

**Issue by victortolbert** [middleman/middleman#117]
By default, the following Compass include...

`+font-face("Museo Sans", font-files("museosans-web.woff", woff, "museosans-web.ttf", truetype)`

results in **file not found errors** even though the fonts are there

```
File not found: source/fonts/museosans-web.woff
File not found: source/fonts/museosans-web.ttf
```

Here is the generated style

``` css
@font-face {
  font-family: "Museo Sans";
  src: url('../../source/fonts/museosans-web.woff') format('woff'), url('../../source/fonts/museosans-web.ttf') format('truetype');
}
```
