### ISSUE TITLE
Nested lists inside local data (YAML or JSON)

### ISSUE THREAD

**Issue by yannlossouarn** [middleman/middleman#1189]
Hi,

I am stuck on using nested lists inside local data, in a HAML template. I tried the same data structure with both a YAML and JSON file, with the same result.

The first list level is 

Here are the data structures:
JSON version

``` json
[
  {
    "importance": "majeur", 
    "titre": "Modification des notifications par e-mail JSON ", 
    "auteur": "FRAN\u00c7OISE", 
    "historique": [
      {
        "item": {
          "date": "2014-01-01", 
          "label": "Cr\u00e9ation"
        }
      }, 
      {
        "item": {
          "date": "2014-01-02", 
          "label": "Ajout d'un commentaire"
        }
      }
    ]
  }, 
  {
    "importance": "mineur", 
    "titre": "Anomalie \u00e0 la cr\u00e9ation d'une fiche ", 
    "auteur": "KARINE"
  }, 
  {
    "importance": "majeur", 
    "titre": "Mise en place d'indicateurs de suivi des fiches ", 
    "auteur": "FRAN\u00c7OISE"
  }, 
  {
    "importance": "majeur", 
    "titre": "Mise en oeuvre de l'enveloppe", 
    "auteur": "KARINE"
  }, 
  {
    "importance": "majeur", 
    "titre": "logistique - non incr\u00e9mentation du num\u00e9ro de fiche ", 
    "auteur": "BRUNO"
  }, 
  {
    "importance": "mineur", 
    "titre": "Propositions d'\u00e9volutions", 
    "auteur": "GENEVI\u00c8VE"
  }, 
  {
    "importance": "mineur", 
    "titre": "Accr\u00e9ditations ", 
    "auteur": "BRUNO"
  }
]
```

YAML version

``` yaml
-
  titre: "Modification des notifications par e-mail YAML "
  auteur: "FRANÇOISE"
  importance: majeur
  historique:
    -
      item:
        date: "2014-01-01"
        label: "Création"
    -
      item:
        date: "2014-01-02"
        label: "Ajout d'un commentaire"
-
  titre: "Anomalie à la création d'une fiche "
  auteur: "KARINE"
  importance: mineur
-
  titre: "Mise en place d'indicateurs de suivi des fiches "
  auteur: "FRANÇOISE"
  importance: majeur
-
  titre: "Mise en oeuvre de l'enveloppe"
  auteur: "KARINE"
  importance: majeur
-
  titre: "logistique - non incrémentation du numéro de fiche "
  auteur: "BRUNO"
  importance: majeur
-
  titre: "Propositions d'évolutions"
  auteur: "GENEVIÈVE"
  importance: mineur
-
  titre: "Accréditations "
  auteur: "BRUNO"
  importance: mineur
```

... and then the HAML code:

``` haml
    - data.autresfiches.each do |item|
      %div.panel.panel-fiche
        %h4= item.titre
        %p= item.auteur
        %p= item.importance
        %i= item.historique
        %p
          item.historique = 
          = item.historique
        %p
          item.historique.class = 
          = item.historique.class
        %p
          item.historique.inspect =
          = item.historique.inspect

        -#%p.doesNotWork
          %p
            item.historique.length = 
            = item.historique.length
        -#%p.doesNotWork2
          - item.historique.each do |evenement|
            %p= evenement['date']
            %i= evenement['commentaire']

        - @histo = item.historique
        %p
          @test = 
          = @histo
        %p
          @test.class = 
          = @histo.class

        %p
          @test.inspect =
          = @histo.inspect

        -#%p.doesNotWork
          %p
            @test.length = 
            = @histo.length
        -#%p.doesNotWork2
          - @histo.each do |evenement|
            %p= evenement['date']
            %i= evenement['commentaire']

```

The output is correct concerning the titre, auteur, and importance fields. I can also display the raw content of the historique field, e.g.:

``` JSON
[{"item"=>{"date"=>"2014-01-01", "label"=>"Création"}}, {"item"=>{"date"=>"2014-01-02", "label"=>"Ajout d'un commentaire"}}] 
```

The object class is "Array", however as soon as I try using an array method, like length or each, I get this kind of error message:

```
NoMethodError at /dashboard.html
undefined method `each' for nil:NilClass
```

Any idea ?
