### ISSUE TITLE
Localized / i18n frontmatter for title & meta content

### ISSUE THREAD

**Issue by dustinhorton** [middleman/middleman#1594]
Is there any support for this, or is something like https://forum.middlemanapp.com/t/i18n-string-translation-and-frontmatter/1267 the best way to make this work?

**Comment by tdreyno** [comment]
Please post the full question here

**Comment by dustinhorton** [comment]
How do I use localized content in frontmatter?

In `en.yml`:
```yaml
en:
  about:
    title: "About"
    description: "Lorem ipsum dolor"
```

In `about.html.haml`:
```haml
---
title: t(:title, scope: [:about])
description: t(:description, scope: [:about])
---
```

Doesn't work.
