### ISSUE TITLE
Issues with dynamic pages/directory indexes - v4

### ISSUE THREAD

**Issue by olliekav** [middleman/middleman#1596]
So I'm trying to output dynamic pages using v4. Which has thrown up some weird issues around directory indexes. Correct me if I'm using the wrong code here but I couldn't find anything noted why this wouldn't work.

*config.rb*
```
data.sneakers.types.each do |sneaker|
  proxy "/#{sneaker.url}.html", "/sneaker-template.html", locals: { 
    sneaker: sneaker
  }, :ignore => true
end

activate :directory_indexes
```

*data/sneakers.yml*
```
types:
  - name: Nike Air Jordan <span class="fade">3</span>
    url: nike-air-jordan-3
    body_class: colorway-grey-cement
    colorways:
      - colorway:
        name: Grey Cement
        class: grey-cement
      - colorway:
        name: Black Cement
        class: black-cement
      - colorway:
        name: True Blue
        class: true-blue
      - colorway:
        name: Stealth
        class: stealth
      - colorway:
        name: Sport Blue
        class: sport-blue
  - name: Nike Air Max <span class="fade">90</span>
    partial: nike_air_max_90
    url: nike-air-max-90
    colorways:
      - colorway:
        name: Infrared
        class: infrared
```

Trying to view the first page on `http://localhost:4567/nike-air-jordan-3/` gives me a 404. If I try through Pow on `http://freshkicks.dev/nike-air-jordan-3/`I get a 404 and using rackup I get a 404 on `http://localhost:9292/nike-air-jordan-3/`.

`/nike-air-jordan-3.html` does work for all though.

If I remove the `.html` file extension from the proxy and add a trailing slash... `proxy "/#{sneaker.url}/"`. I get the following...

```
NameError at /nike-air-jordan-3/
undefined local variable or method `index_file' for #<#<Class:0x007fcea9f24818>:0x007fceaaebc910>

Ruby	/Users/olliekav/.rvm/gems/ruby-2.2.0@freshkicks/bundler/gems/middleman-d849930e511b/middleman-core/lib/middleman-core/core_extensions/default_helpers.rb: in page_classes, line 138
Web	GET localhost/nike-air-jordan-3/
```

If I remove the trailing slash... `proxy "/#{sneaker.url}"`. The pages load. Am I missing something that has been changed? Or am I doing something wrong?
