### ISSUE TITLE
Middleman 4: font-url generates absolute path when :relative_assets is activated

### ISSUE THREAD

**Issue by jimothyGator** [middleman/middleman#1689]
The relative_assets plugin doesn't appear to work with fonts, at least not when using Compass `font-url` function. An absolute URL is still generated. Tested against rc1 and master.

Also tested against Middleman 3.4 and 3.3, where it works correctly.

### source/stylesheets/site.css.scss
```sass
@font-face {
    font-family: 'Roboto';
    src: font-url('roboto/roboto-regular-webfont.eot');
    src: font-url('roboto/roboto-regular-webfont.eot?#iefix') format('embedded-opentype'),
         font-url('roboto/roboto-regular-webfont.woff') format('woff'),
         font-url('roboto/roboto-regular-webfont.ttf') format('truetype'),
         font-url('roboto/roboto-regular-webfont.svg#robotoregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

### config.rb
```ruby
set :fonts_dir, 'fonts'

configure :build do
  activate :relative_assets
end
```

### build/stylesheets/site.css
```css
@font-face {
  font-family: 'Roboto';
  src: url(/fonts/roboto/roboto-regular-webfont.eot);
  src: url(/fonts/roboto/roboto-regular-webfont.eot?#iefix) format("embedded-opentype"), url(/fonts/roboto/roboto-regular-webfont.woff) format("woff"), url(/fonts/roboto/roboto-regular-webfont.ttf) format("truetype"), url(/fonts/roboto/roboto-regular-webfont.svg#robotoregular) format("svg");
  font-weight: normal;
  font-style: normal; }
```

**Comment by jimothyGator** [comment]
Upon further investigation, I see that if i use `url` instead of `font-url`, it works (with the exception of the `.eot` extension, which is easy enough to resolve through configuration). But it doesn't work with the `font-url`Compass function.

**Comment by jimothyGator** [comment]
It appears the problem is that Compass doesn't quote the URL; if I take the output from `build/stylesheets/site.css` and paste it into `source/site.css.scss`, a similar problem occurs. The first URL is made relative, but the remainder stay absolute.

If I the quote the values, as follows, all URLs (except those with an `.eot` suffix, as expected) are adjusted appropriately.

```css
@font-face {
  font-family: 'Roboto';
  src: url('/fonts/roboto/roboto-regular-webfont.eot');
  src: url('/fonts/roboto/roboto-regular-webfont.eot?#iefix') format("embedded-opentype"), url('/fonts/roboto/roboto-regular-webfont.woff') format("woff"), url('/fonts/roboto/roboto-regular-webfont.ttf') format("truetype"), url('/fonts/roboto/roboto-regular-webfont.svg#robotoregular') format("svg");
  font-weight: normal;
  font-style: normal; }
```

Trying to see if I can force Compass to quote the URLs.

**Comment by jimothyGator** [comment]
I've continued to look into this. The `url(...)` syntax is generated by a combination of Middleman and Sprockets. [Middleman generates the path](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util.rb#L202) (`/fonts/foo.woff`), and (Sprockets wraps)[https://github.com/sstephenson/sprockets/blob/master/lib/sprockets/sass_functions.rb#L41] it (`url(/fonts/foo.woff').

Sprockets should probably add the quotes. However, Middleman 3.x didn't require quotes to correctly translate to a relative path.

**Comment by tdreyno** [comment]
I think this is a regression in v4's pattern matching

**Comment by jimothyGator** [comment]
That seems to be the case; a regression in the pattern matching. Here's a simplified example that takes the `font-url` function and `eot` format out of the picture.

Source:

```css
@font-face {
  font-family: 'QuotedFont';
  src:  url('/fonts/roboto/roboto-regular-webfont.woff') format("woff"), 
        url('/fonts/roboto/roboto-regular-webfont.ttf') format("truetype"),
        url('/fonts/roboto/roboto-regular-webfont.svg#robotoregular') format("svg");
  font-weight: normal;
  font-style: normal; 
}

@font-face {
  font-family: 'UnquotedFont';
  src:  url(/fonts/roboto/roboto-regular-webfont.woff) format("woff"), 
        url(/fonts/roboto/roboto-regular-webfont.ttf) format("truetype"),
        url(/fonts/roboto/roboto-regular-webfont.svg#robotoregular) format("svg");
  font-weight: normal;
  font-style: normal; 
}
```

Output (slightly re-formated for readability)

```css
@font-face {
  font-family: 'QuotedFont';
  src: url("../fonts/roboto/roboto-regular-webfont.woff") format("woff"), 
    url("../fonts/roboto/roboto-regular-webfont.ttf") format("truetype"), 
    url("../fonts/roboto/roboto-regular-webfont.svg#robotoregular") format("svg");
  font-weight: normal;
  font-style: normal; }

@font-face {
  font-family: 'UnquotedFont';
  src: url(../fonts/roboto/roboto-regular-webfont.woff) format("woff"), 
    url(/fonts/roboto/roboto-regular-webfont.ttf) format("truetype"), 
    url(/fonts/roboto/roboto-regular-webfont.svg#robotoregular) format("svg");
  font-weight: normal;
  font-style: normal; }
}
```

Notice that when, in the source, the URLs are quoted, Middleman correctly generates absolute paths for all the URLs. When the URLs are not quoted, only the first URL (`woff` in this example) gets translated.
