### ISSUE TITLE
asset_hash rewriter doesn't rewrite specific CSS files with `content: " "` 

### ISSUE THREAD

**Issue by bradgessler** [middleman/middleman#1852]
Given the CSS file `./source/stylesheets/bug.css`:

```css
.no-bug{background-image:url(/images/middleman-logo.svg)}
.bug{content:"";background-image:url(/images/middleman-logo.svg)}
.no-bug{content:""; background-image:url(/images/middleman-logo.svg)}
```

and the `config.rb` file:

```ruby
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

# Build-specific configuration
configure :build do
  activate :asset_hash
end
```

When I request the resource `http://127.0.0.1:4567/stylesheets/bug-ff7fb4c7.css`:

```css
.no-bug{background-image:url(/images/middleman-logo-257e02f7.svg)}
.bug{content:"";background-image:url(/images/middleman-logo.svg)}
.no-bug{content:""; background-image:url(/images/middleman-logo-257e02f7.svg)}
```

The url in the `.bug` class doesn't get rewritten because of the `content:""` attribute without a following space.

This problem exhibited itself when an asset with a `content: ""` attribute in a class comes before any other attribute.

I suspect the regexp at https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util/rack.rb#L25 is the source of the issue. Working through that expression ATM to figure out what its trying to parse.
