### ISSUE TITLE
asset_hash does not work with layered backgrounds

### ISSUE THREAD

**Issue by sys7emshock** [middleman/middleman#2100]
```css
#awesomeDiv {
  background: url(../images/amazing-background.jpg);
}

#sadDiv {
  background: -webkit-linear-gradient(
      0deg,
      rgba(40, 160, 160, 0.9),
      rgba(85, 175, 200, 0.95),
      rgba(90, 145, 200, 0.9)
    ),
    url(../images/sad-background.jpg);
}
```

## Expected output
Both image urls should be replaced with the respective asset hashed urls.

## Actual behavior
While the url is successfully replaced in `#awesomeDiv`, but not in `#sadDiv`

## Steps to reproduce the problem (from a clean middleman installation)
Make a simple page with two divs, and use the css snippet provided above.

## Additional information

- Ruby version: 2.4.1
- Middleman version: 3.4.1
- OS version: macOS Sierra
