### ISSUE TITLE
Data files containing integers as keys raises error

### ISSUE THREAD

**Issue by leighmcculloch** [middleman/middleman#2238]
## Expected behavior and actual behavior

In older versions of middleman (v3) a data file that has integer keys could be ingested. In the latest stable release of middleman (v4.2.1) a data file with integer keys will cause an error like:

```
YAML Exception parsing /home/.../data/apps.yml: undefined method `to_sym' for 2005:Integer
Did you mean?  to_s
```

## Steps to reproduce the problem (from a clean middleman installation)

Add a YAML file to the data file (e.g. `apps.yaml`) like so:

```yaml
timeline:                                      
  2005:                                        
    - key: app1                            
      name: Best app ever                           
      description: A great app.
```

Reference the data file in a page by calling a function on it iterating, like:

```ruby
data.apps.timeline.each do |year, apps|
  ...
end
```

## Additional information

- Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]`
- Middleman version: `4.2.1`
- OS version: `Debian Buster`
