### ISSUE TITLE
FYI: GitHub Actions - Middleman + Webpack

### ISSUE THREAD

**Issue by chrishough** [middleman/middleman#2289]
If you are setting up your site to run on GitHub Actions to deploy to GitHub Pages, here is my [workflow](https://github.com/chrishough/aboutchrishough.com/blob/master/.github/workflows/continuous-integration-workflow.yml). 

```
name: Auto Deployment to Github Pages

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    # ----------------------------------------------------Ruby
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Ruby Version
      run: |
        ruby -v
    - name: Setup Ruby Dependencies
      run: |
        gem update bundler
        bundle install --jobs 4 --retry 3
    - name: Test Ruby Dependencies
      run: |
        bundle exec rake -T
    # ----------------------------------------------------Node
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        version: 10.16.3
    - name: Node Version
      run: |
        node --version
    - name: Setup Node Dependencies
      run: |
        npm install
    # ----------------------------------------------------Webpack
    - name: Build Webpack File
      run: |
        bundle exec rake webpack:build:production
    - name: Build Middle Site
      run: |
        export TERM=xterm
        bundle exec middleman build -e production --verbose
    # ----------------------------------------------------Deploy
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
```

**Comment by tdreyno** [comment]
Fantastic

**Comment by jltml** [comment]
I know this is super old, but in case someone like me stumbles upon it, [here's what I have](https://github.com/jltml/jltml.github.io/blob/source/.github/workflows/gh-pages.yml) (I had to add ZeroMQ to get it to work, & I commented out things I didn't need):

```yaml

# Based on https://github.com/middleman/middleman/issues/2289
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # ----------------------------------------------------Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Ruby Version
        run: |
          ruby -v
      - name: Setup Ruby Dependencies
        run: |
          gem update bundler
          bundle install --jobs 4 --retry 3
      - name: Install ZeroMQ
        run: |
          sudo apt-get install libzmq3-dev
      #- name: Test Ruby Dependencies
      #  run: |
      #    bundle exec rake -T
      # ----------------------------------------------------Node
      #- name: Install Node
      #  uses: actions/setup-node@v1
      #  with:
      #    version: 10.16.3
      #- name: Node Version
      #  run: |
      #    node --version
      #- name: Setup Node Dependencies
      #  run: |
      #    npm install
      # ----------------------------------------------------Webpack
      #- name: Build Webpack File
      #  run: |
      #    bundle exec rake webpack:build:production
      - name: Build Middleman Site
        run: |
          bundle exec middleman build
      # ----------------------------------------------------Deploy
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v1.1.0
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build

```

Make sure to create a [personal GitHub token](https://github.com/settings/tokens) with repo scope and add it to your repo as a repository secret with the name `ACCESS_TOKEN`.
