### ISSUE TITLE
i18n fallback broken when "mount_at_root: false" since v4.4.0

### ISSUE THREAD

**Issue by phvega** [middleman/middleman#2596]
## Expected behavior and actual behavior

Since middleman 4.4.0, `ruby-i18n` version 1.6.0 is used (was 0.9.0) which introduces a breaking change where default locale fallback has to be specified ("en" is not used a default fallback no more). #2507 added a fix for this but it doesn't take into account `mount_at_root: false`, disabling localization fallback when this option is set.

So, if locales are:

```yml
---
en:
  path1: Path 1
  missingTrans: This was localized with helper t(...)
```
```yml
---
es:
  path1: Ruta 1
```

The generated spanish HTMLs will show:

```html
<h3>Ruta 1</h3>

<p>translation missing: es.missingTrans</p>
```

## Steps to reproduce the problem (from a clean middleman installation)

I added a missing translation to [this test repository](https://github.com/phvega/mnt_at_root-test) on the spanish locale which can be seen at `/es/path1.html`.

## Additional information

- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-linux]
- Middleman version: since `4.4.0` and `master`
- OS version: Ubuntu 20.04.1
