### ISSUE TITLE
3.0.0.beta.2 bug: YAML error with tab indented lists.

### ISSUE THREAD

**Issue by jannisg** [middleman/middleman#384]
Hi,

I have just upgraded to 3.x and started a new project using it and have found that I am getting `YAML` errors when using tabs instead of spaces for indentation.

Here is the example from the top of my `index.html.erb` file:

``` yaml

---
title: "Homepage"

navigation:
    - Design
    - Photography
    - Video
    - Blog

---

<%= partial 'partials/header' %>
…
```

**Note the 1 tab indent for list items.**

The moment I remove the tabs and either use spaces or no space at the beginning of the line at all everything works fine again.

Would be awesome if someone could take a look at this, I would if I had any Ruby skills but I am not quite there yet I'm afraid, so my contributions at this stage will be limited to posting bugs not fixing them myself. 
Rest assured I'm learning Ruby at the moment so soonish I will be able to contribute more.

Thanks for reading.
