### ISSUE TITLE
Template engine helpers

### ISSUE THREAD

**Issue by adamesque** [middleman/middleman#527]
In previous versions of Middleman, I used to be able to call a template engine helper directly to render some content. The main use-case was to render Markdown embedded one of the `/data` directory's YAML files (sort of a poor man's sitemap) inside an erb template.
### YAML

``` yaml
-
  name: First thing
  content: A [link](http://link.com) to something
-
  name: Second thing (etc)
```
### ERB

``` erb
<div class="content">
  <%= markdown item.content %>
</div>
```

I'm not sure this was ever an intended use-case, but these template engine helpers aren't included in 3.0 (or if there's an easy way to re-enable them, I haven't figured out how).
