### ISSUE TITLE
Parse localization Yaml data

### ISSUE THREAD

**Issue by RobertCordes** [middleman/middleman#608]
Hey,

I have a question about parsing Yaml data. Basically I would like my `en.yml` to look like this:

```

---
en:
  start:
    headline: "Welcome to ..."
    teaser: "Lorem ipsum dolor"

  about_us:
    headline: "Lorem ipsum dolor"
    ...
```

The problem is that I can't figure out how to properly use the `I18n.t` helper in this case.
