### ISSUE TITLE
feature request: multi-level hash array in locales files.

### ISSUE THREAD

**Issue by mrbinky3000** [middleman/middleman#720]
It would be nice if I could do something like this in a locales yml file:

``` yml

---
en:
  lightbulbs:
    headline: "Amaze-balls lightbulbs"
    pitch: "Check out our totally amaze-balls lightbulb collection."
  frisbees:
    headline: "Fetching Frisbees"
    pitch: "You'll never want to put down our frisbees! Buy one now!"
  widget:
    headline: "Wicked Widgets"
    pitch: "Be the envy of your friends with our widgets!"
```

The file works, but I'm unsure how to reference the sub-keys.

``` haml
%p
    = I18n.t(:lightbulbs)
%p
    = I18n.t(:lightbulbs => 'headline')
```

I suspect that something might have to be altered in the I18n class to allow us to drill down.  Apologies if this can be done already.  If it can be done, can someone provide an example?
