### ISSUE TITLE
Toggle Locale

### ISSUE THREAD

**Issue by mrrooijen** [middleman/middleman#727]
Is there any good way to toggle between locales when you use the special `en.paths` key?

For example:

``` yml
en:
  paths:
    about: "about"

nl:
  paths:
    about: "over-ons"
```

When you're on `/en/about` and you want to toggle language to Dutch `/nl/over-ons` how do you generate a link that will also correctly update the URL? My current functionality would cause this to happen: `/nl/about` or `/en/over-ons` when trying to toggle. I can't really find anything that's built-in that handles this scenario. Is there? If not, how do others deal with this?

Thanks
