### ISSUE TITLE
Localizing directory names 

### ISSUE THREAD

**Issue by rjewson** [middleman/middleman#911]
I have a site with basic localization working fine.  My filename 'testFile.html.erb' located in the root of /localizable gets translated with the following:

```
en:
  hello: "hello"
  paths:
    testFile: "testFile_i18n"
```

If I add a folder at the the following location /localizable/folder1 and add a file to it, I can translate the new filename by adding it to the paths definition above, but how do I localize the folder name 'folder1'?  I didn't see any reference to this in the documentation and our use case requires fully localizable paths, not just files.
